"use client";
import { useState } from "react";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [collapsed, setCollapsed] = useState(false);

  const toggleSidebar = () => {
    setCollapsed(!collapsed);
  };

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ToastContainer />

          <div className="flex">
            <Sidebar collapsed={collapsed} toggleSidebar={toggleSidebar} />
            <div
              className={`flex-1 transition-all duration-300 ${
                collapsed ? "" : "ml-60"
              }`}
            >
              <Navbar toggleSidebar={toggleSidebar} collapsed={collapsed} />
              <main className="p-6">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
